-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        active_opacity = 0.9,
        fullscreen_opacity = 0.9,
        inactive_opacity = 0.9,
        rounding = 5,
    },
    general = {
        gaps_in = 3,
        gaps_out = 4,
    },
})

-- Keybinds
hl.unbind("SUPER + RETURN")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("alacritty"))
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("/usr/bin/brave-browser-stable"))
